version: '3.8'
services:
  java-app-db:
    image: truxxt/java-login-db:2
    ports:
      - "3306:3306"
    volumes:
      - java-login-dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Admin123

  java-login-app:
    image: truxxt/java-login-app:v2
    ports:
      - "8080:8080"
    volumes:
      - java-login-appdata:/usr/local/tomcat/webapps

  java-login-web:
    image: truxxt/java-login-web:v2
    ports:
      - "80:80"
    

volumes:
  java-login-dbdata: {}
  java-login-appdata: {}